name: tmt_dart_utils
description: The sets of utilities and extension method for Dart projects.
version: 1.2.8
repository: https://github.com/namhi/tmt_flutter_utils/tree/master/packages/tmt_dart_utils


environment:
  sdk: '>=3.0.6 <4.0.0'
dependencies:
  intl: '>=0.17.0 <=0.19.0'
  diacritic: ^0.1.3
  timeago: ^3.3.0
  crypto: ^3.0.2
  collection: '>=1.17.1 <2.0.0'
  path: '>=1.8.3 <2.0.0'


dev_dependencies:
  flutter_lints: ^2.0.0
  test: ^1.25.7
