name: tmt_flutter_utils
description:  Extension method and utils library using for flutter project.
version: 1.1.0
author: Nguyễn Văn Nam
homepage: namnv.me

publish_to: none

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  intl: ^0.17.0
  diacritic: ^0.1.3
  timeago: ^3.0.2
  crypto: ^3.0.0

  flutter:
    sdk: flutter
  collection: ^1.15.0-nullsafety.4

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter: