name: tmt_flutter_utils_workspace
publish_to: none

workspace:
  - packages/tmt_dart_utils
  - packages/tmt_flutter_utils

environment:
  sdk: ">=3.7.0 <4.0.0"

dev_dependencies:
  melos: ^7.5.1

melos:
  sdkPath: .fvm/flutter_sdk
