name: tmt_flutter_utils
description:  Extension method and utils library using for flutter project.
version: 1.1.9
homepage: namnv.me
publish_to: none
repository: https://github.com/namhi/tmt_flutter_utils.git
issue_tracker: https://github.com/namhi/tmt_flutter_utils/issues

platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: '>=2.17.0 <3.0.0'ÏÏÏ

dependencies:
  intl: ^0.17.0
  diacritic: ^0.1.3
  timeago: ^3.3.0
  crypto: ^3.0.2
  tmt_dart_utils:
    git:
      url: https://github.com/namhi/tmt_flutter_utils.git
      path: packages/tmt_dart_utils/

  flutter:
    sdk: flutter


dev_dependencies:
  flutter_test:
    sdk: flutter
